development:
  twilio_account_sid: 'sddsd'
  twilio_auth_token: "sadsad"
  twilio_phone_number: 'asdad'
  smtp_send_from: 'vadasddaso@gmail.com'
  smtp_password: 'wzdsadasdf'
  smtp_username: 'vdsasdds.com'
